config/routes.rb
Rails.application.routes.draw do
  resources :sells, only: %i[new create]
  resources :books, only: %i[new create]
  root 'dashboard#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true

  has_many :sells

  after_create_commit :set_book_graph

  def lastest_sells
    array = Array.new

    sells.each do |sell|
      array.push(sell.quantity)
    end

    array
  end

  private

  def set_book_graph
    broadcast_append_to("books_custom_channel", partial: 'dashboard/graphs/book', locals: { book: self }, target: 'books_section_graphs')
  end
end

app/models/sell.rb
class Sell < ApplicationRecord
  belongs_to :book

  validates :quantity, presence: true
  validates :day, presence: true

  before_create :calculate_total

  after_create_commit :set_sells_graphs

  DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

  private

  def calculate_total
    book_price = book.price
    self.total = book_price * quantity
  end

  def set_sells_graphs
    broadcast_replace_to("sells_custom_channel", partial: 'dashboard/graphs/days', locals: {}, target: 'days_section_chart')
    broadcast_replace_to("sells_custom_channel", partial: 'dashboard/graphs/revenue', locals: {}, target: 'revenue_section_chart')
    broadcast_replace_to("sells_custom_channel", partial: 'dashboard/graphs/book', locals: {book: book}, target: "#{book.id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params

    if @book.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def book_params
    params.require(:book).permit(:name, :price)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  before_action :set_book, only: %i[create]
  def new
    @sell = Sell.new
  end

  def create
    @sell = @book.sells.new sell_params

    if @sell.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def sell_params
    params.require(:sell).permit(:quantity, :day)
  end

  def set_book
    @book = Book.find(params[:sell][:book_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def revenue_from_sells
    array = Array.new

    Book.all.each do |book|
      array.push([book.name, book.sells.sum(:total).round(2)])
    end

    array
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sells_helper.rb
module SellsHelper
  def sells_from_days
    array = Array.new

    Sell::DAYS.each do |day|
      array.push([day, Sell.where(day: day).sum(:quantity)])
    end

    array
  end
end

app/views/books/_form.html.erb
<%= turbo_frame_tag 'add_new_book', class: 'flex items-center w-full ml-10' do %>
  <div class="flex w-full items-center" data-controller="form">
    <%= form_with(model: book, class:'flex w-full items-center', data: { controller: 'form', action: 'submit->form#resetForm' }) do |f| %>

      <% if book.errors.any? %>
        <div class="bg-red-200 rounded p-2 flex flex-col mx-2">
          <% book.errors.each do |error| %>
            <p class="text-xs font-semibold text-red-800">- <%= error.full_message %></p>
          <% end %>
        </div>
      <% end %>

      <div class="flex items-center gap-1 ml-2">
        <%= f.label :name, 'Name:', id: 'book_name_label', class: 'font-semibold text-white' %>
        <%= f.text_field :name, id: 'book_name_input', class: 'font-semibold rounded p-2 text-xs' %>
      </div>

      <div class="flex items-center gap-1 ml-2">
        <%= f.label :price, 'Price:', id: 'book_name_label', class: 'font-semibold text-white' %>
        <%= f.number_field :price, in: 1.0..100.0, step: :any, id: 'book_name_input', class: 'font-semibold rounded p-2 text-xs' %>
      </div>

      <div class="flex items-center justify-end gap-2 ml-5">
        <%= link_to 'Cancel', :back, id: 'cancel_book', class: 'font-semibold p-2 bg-red-600 text-sm text-white rounded' %>
        <%= f.submit id: 'submit_book', class: 'font-semibold p-2 bg-sky-600 text-sm text-white rounded' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/new.html.erb
<%= render 'books/form', book: @book %>

app/views/dashboard/components/_book_graph.html.erb
<div class="flex flex-col my-5 rounded-lg py-4 px-10 border shadow-lg bg-gray-100">
  <div class="font-semibold text-xl text-center my-5">
    <%= book.name %>
  </div>
  <div class="flex items-center justify-center">
    <%= line_chart book.lastest_sells,  xtitle: "Days", ytitle: "Quantity", width: "350px", height: "200px", curve: false %>
  </div>
</div>

app/views/dashboard/components/_books_section.html.erb
<div class="flex flex-col w-2/6">
  <h4 class="text-white text-2xl font-semibold text-center my-5">Boook's Lastest Sells.</h4>

  <div id="books_section_graphs" class="overflow-y-auto h-[800px]">
    <% Book.order(:created_at).each do |book| %>
      <%= render 'dashboard/graphs/book', book: book %>
    <% end %>
  </div>
</div>

app/views/dashboard/components/_days_section.html.erb
<div class="flex flex-col w-2/6">
  <h4 class="text-white text-2xl font-semibold text-center my-5">Days of the week.</h4>
  <%= render 'dashboard/graphs/days' %>
</div>

app/views/dashboard/components/_earnings_section.html.erb
<div class="flex flex-col w-2/6">
  <h4 class="text-white text-2xl font-semibold text-center my-5">Earnings.</h4>
  <%= render 'dashboard/graphs/revenue' %>
</div>

app/views/dashboard/components/_title.html.erb
<section class="flex flex-col items-center justify-center w-full mt-14 mb-5">
  <div class="flex flex-col items-center">
    <h1 class="font-bold text-4xl text-white my-5">The Bookstore Dashboard App - Ruby on Rails 7.</h1>
    <p class="text-sm text-white">This is the Dashboard App built using Ruby on Rails 7 and Hotwire</p>
  </div>
</section>

app/views/dashboard/graphs/_book.html.erb
<div class="flex flex-col my-5 rounded-lg py-4 px-10 border shadow-lg bg-gray-100" data-controller="book"
  data="<%= book.lastest_sells %>" book="<%= book.id %>" id="<%= book.id %>">
  <div class="font-semibold text-xl text-center my-5" data-action="click->book#isLoaded">
    <%= book.name %>
  </div>
  <canvas id="chart_<%= book.id %>" style="width:100%;max-width:700px"></canvas>
</div>

app/views/dashboard/graphs/_days.html.erb
<div data-controller="day" class="flex flex-col my-5 rounded-lg py-4 px-10 border shadow-lg bg-gray-100"
  id="days_section_chart" data="<%= sells_from_days %>">
  <div class="font-semibold text-xl text-center my-5">
    Most sells of the week.
  </div>
  <div class="items-center flex flex-col">
    <canvas id="days_chart" style="width:90%;max-width:700px"></canvas>
  </div>
</div>

app/views/dashboard/graphs/_revenue.html.erb
<div data-controller="revenue" id="revenue_section_chart" data="<%= revenue_from_sells %>"
  class="flex flex-col my-5 rounded-lg py-4 px-10 border shadow-lg bg-gray-100 justify-center">
  <div class="font-semibold text-xl text-center my-5">
    Reveue from the Bookstore.
  </div>

  <div class="flex items-center justify-center h-72">
    <canvas id="revenue_chart"></canvas>
  </div>

  <div class="mt-5 flex flex-col">
    <h5 class="font-bold text-center my-5 text-xl">Sells for each book</h5>
    <table class="my-5">
      <div class="flex w-full">
        <div class="w-1/3 flex items-center font-semibold border-2 justify-center text-sm text-center">ID</div>
        <div class="w-1/3 flex items-center font-semibold border-2 justify-center text-sm text-center">Name</div>
        <div class="w-1/3 flex items-center font-semibold border-2 justify-center text-sm text-center">Revenue</div>
      </div>
      <div class="flex flex-col">
        <% Book.all.each do |book| %>
          <div class="flex">
            <div class="w-1/3 flex items-center font-semibold border-2 justify-center text-sm text-center"><%= book.id %></div>
            <div class="w-1/3 flex items-center font-semibold border-2 justify-center text-sm text-center"><%= book.name %></div>
            <div class="w-1/3 flex items-center font-semibold border-2 justify-center text-sm text-center">$<%= book.sells.sum(:total).round(2) %> USD</div>
          </div>
        <% end %>
      </div>
    </table>
  </div>

  <div class="flex flex-col w-full items-center">
    <h4 class="font-bold">Total revenue.</h4>
    <span class="font-bold text-xl">$ <%= Sell.all.sum(:total).round(2) %> USD</span>
  </div>
</div>

app/views/dashboard/index.html.erb
<%= turbo_stream_from "books_custom_channel" %>
<%= turbo_stream_from "sells_custom_channel" %>
<main class="flex flex-col">
  <%= render 'shared/side_bar' %>

  <section class="flex flex-col w-full">

    <div class="flex">
      <%= render 'dashboard/components/title' %>
    </div>

    <div class="flex gap-3 m-5 p-5 rounder border border-gray-600 rounded-lg shadow-lg shadow-white/20">
      <%= render 'dashboard/components/days_section' %>
      <%= render 'dashboard/components/earnings_section' %>
      <%= render 'dashboard/components/books_section' %>
    </div>
  </section>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-black">
    <%= yield %>
  </body>
</html>

app/views/sells/_form.html.erb
<%= turbo_frame_tag 'add_sell', class: 'flex items-center justify-center' do %>
  <div class="flex items-center w-full" data-controller="form">
    <%= form_with(model: sell, class:'flex items-center w-full', data: { controller: 'form', action: 'submit->form#resetForm' }) do |f| %>

      <% if sell.errors.any? %>
        <div class="bg-red-200 rounded p-2 flex flex-col mx-2">
          <% sell.errors.each do |error| %>
            <p class="text-sm font-semibold text-red-800">- <%= error.full_message %></p>
          <% end %>
        </div>
      <% end %>

      <div class="flex items-center gap-1 ml-2">
        <%= f.label :book_name, 'Book:', id: 'label_book_name', class: 'text-sm font-semibold text-white' %>
        <%= f.select(:book_id,  Book.all.collect {|book| [ book.name, book.id ] }, { include_blank: true },
          { class: 'font-semibold rounded p-2 text-xs w-full', id: 'select_book_name'})
        %>
      </div>

      <div class="flex items-center gap-1 ml-2">
        <%= f.label :quantity, 'Quantity: ', id: 'sell_name_label', class: 'text-sm font-semibold text-white' %>
        <%= f.number_field :quantity, id: 'sell_name_input', class: 'font-semibold rounded p-2 text-xs w-full' %>
      </div>

      <div class="flex items-center gap-1 ml-2">
        <%= f.label :day, 'Day of the week:', id: 'label_day', class: 'text-sm font-semibold text-white' %>
        <%= f.select(:day, Sell::DAYS.map { |option| [option.humanize, option] }, { include_blank: true },
          { class: 'font-semibold rounded p-2 text-xs w-full', id: 'select_day'})
        %>
      </div>

      <div class="flex items-center justify-end gap-2 ml-5">
        <%= link_to 'Cancel', :back, id: 'cancel_sell', class: 'font-semibold p-2 bg-red-600 text-sm text-white rounded' %>
        <%= f.submit id: 'submit_sell', class: 'font-semibold p-2 bg-green-600 text-sm text-white rounded' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/sells/new.html.erb
<%= render 'sells/form', sell: @sell  %>

app/views/shared/_side_bar.html.erb
<nav class="w-full flex bg-black items-center p-5 justify-between fixed">
  <div class="flex gap-5 items-center">
    <%= image_tag('book.png', class: 'w-10') %>
    <h3 class="font-bold text-lg text-white">The Bookstore Dashboard</h3>
  </div>

  <div class="flex gap-5">
    <%= turbo_frame_tag 'add_sell', class: 'flex items-center justify-center' do %>
      <%= link_to new_sell_path, id: 'add_sell_link', class: 'text-white font-semibold text-sm text-center bg-green-700 text-white rounded px-4 py-2' do %>
        Add sell
      <% end %>
    <% end %>

    <%= turbo_frame_tag 'add_new_book', class: 'flex items-center justify-center' do %>
      <%= link_to new_book_path, id: 'add_new_book_link', class: 'text-white font-semibold text-sm text-center bg-sky-700 text-white rounded px-4 py-2' do %>
        Add a new book
      <% end %>
    <% end %>
  </div>
</nav>